image: ubuntu:16.04

stages:
  - build
  - tests

default:
  before_script:
    - apt-get update -y
    - apt install curl zip unzip wget -y
    - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
    - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
    - apt-get update
    - apt install google-chrome-stable -y
    - curl -s "https://get.sdkman.io" | bash
    - source "$HOME/.sdkman/bin/sdkman-init.sh"
    - sdk version
    - sdk ls java
    - sdk install java 8.0.302-open

build:
  stage: build
  script:
    - ./gradlew assemble

automation_tests:
  stage: tests
  script:
    - chmod +x gradlew
    - ./gradlew test allureReport
  artifacts:
    name: "Allure report"
    paths:
      - build/reports/allure-report/